ALTER TABLE Plano_Assinatura ADD COLUMN Academia_ID VARCHAR(14) REFERENCES Academia(CNPJ) ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE Matricula ADD COLUMN Academia_ID VARCHAR(14) REFERENCES Academia(CNPJ) ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE Plano_Exercicios ADD COLUMN Academia_ID VARCHAR(14) REFERENCES Academia(CNPJ) ON DELETE RESTRICT ON UPDATE CASCADE;
