ALTER TABLE Plano_Exercicios ADD COLUMN Equipamento_ID INT REFERENCES Equipamento (ID_Equipamento) ON DELETE CASCADE ON UPDATE RESTRICT;

ALTER TABLE Plano_Assinatura ADD COLUMN Cliente_ID VARCHAR(11) REFERENCES Cliente (CPF_Cliente) ON DELETE CASCADE ON UPDATE RESTRICT;
